name: pyvista-environment
channels:
  - bokeh/label/dev
dependencies:
  - python
  - bokeh
  - pip
  - pyviz_comms
  - panel
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - matplotlib
    - git+git://github.com/OpenGeoVis/omfvista@master
    - pyct
